/* Generated by site/build.py — do not edit.
 * Keeps the role generator working with no signal. Only the tool page and its assets are
 * handled; every other request on the site passes straight through to the network. */
var CACHE = "rps-tools-2125719a";
var TOOLS = ["/tools/role-generator/"];
var ASSETS = ["/tools/role-generator/", "/assets/site.css", "/assets/fonts.css", "/assets/js/deck.js?v=2125719a", "/assets/js/generator.js?v=2125719a", "/assets/icon-192.png", "/assets/icon-512.png", "/assets/favicon.png", "/assets/favicon-48.png", "/assets/favicon-96.png", "/assets/fonts/cormorant-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYp3tKky2F7i6C.woff2", "/assets/fonts/cormorant-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYpHtKky2F7i6C.woff2", "/assets/fonts/cormorant-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYpntKky2F7i6C.woff2", "/assets/fonts/cormorant-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYqXtKky2F7g.woff2", "/assets/fonts/cormorant-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYrXtKky2F7i6C.woff2", "/assets/fonts/cormorant-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd5wDD-h9M8A_6pUKz9ugk.woff2", "/assets/fonts/cormorant-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd5wDD-hdM8A_6pUKz9ugk.woff2", "/assets/fonts/cormorant-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd5wDD-htM8A_6pUKz9ugk.woff2", "/assets/fonts/cormorant-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd5wDD-iNM8A_6pUKz9.woff2", "/assets/fonts/cormorant-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd5wDD-jNM8A_6pUKz9ugk.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa0ZL7W0Q5n-wU.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1pL7W0Q5n-wU.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa25L7W0Q5n-wU.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa2JL7W0Q5n-wU.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa2ZL7W0Q5n-wU.woff2", "/assets/fonts/inter-UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa2pL7W0Q5n-wU.woff2"];
self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }).then(function () { return self.skipWaiting(); }));
});
self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});
self.addEventListener("fetch", function (e) {
  var url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  var path = url.pathname + (url.search || "");
  if (e.request.mode === "navigate" && TOOLS.indexOf(url.pathname) !== -1) {
    // Network first so a deploy shows up; the cached page is the fallback when there is no signal.
    e.respondWith(fetch(e.request).then(function (r) {
      var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(url.pathname, copy); }); return r;
    }).catch(function () { return caches.match(url.pathname); }));
    return;
  }
  if (ASSETS.indexOf(path) !== -1 || ASSETS.indexOf(url.pathname) !== -1) {
    e.respondWith(caches.match(e.request).then(function (hit) { return hit || fetch(e.request); }));
  }
});
